### ISSUE TITLE
android App

### ISSUE THREAD

**Issue by joihn** [giech/arduinotaskerbluetooth#1]
Hello,

your serial bluetooth app is working well on my LG G4 :) Right out of the box my bluetooth device worked ! 

the only bluetooth app on app apstore currently is this one :
https://play.google.com/store/apps/details?id=appinventor.ai_rblackmore245.Arduino_Bluetooth

You should post your own app !

Thanks for you work

**Comment by giech** [comment]
Thanks for your good feedback! I would like to eventually post the APK on the store. It requires a bit of a preparation, so it might take a while, so I'll leave the issue open for now.

**Comment by giech** [comment]
The app is finally published on [Google Play](https://play.google.com/store/apps/details?id=com.giechaskiel.ilias.bluetoothserialfromtasker)!
